services:
  api:
    build: .
    container_name: projetocarol_api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mysql_shared;Port=3306;Database=ProjetoCarolDb;User=devuser;Password=${DB_PASSWORD};
      - JWT__Key=${JWT_KEY}
    volumes:
      - uploads_data:/app/uploads
    networks:
      - mysql_shared_net

networks:
  mysql_shared_net:
    external: true

volumes:
  uploads_data: